# Performs unit and integration testing

name: Validations CI

# The events that trigger the workflow
on:
  pull_request:
    branches: [ develop ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    name: ${{ matrix.name }}

    strategy:
      fail-fast: false  # Prevents cancellation of remaining jobs if one fails
      matrix:
        include:
          - name: Spline Validations
            ntests: 1
            test_1: Apps/SplineValidations

          - name: Covariance Validations
            ntests: 2
            test_1: Apps/CovarianceValidations
            test_2: Apps/MaCh3ModeValidations

          - name: Fitter Validations
            ntests: 6
            test_1: Apps/FitterValidations
            test_2: ./bin/ProcessMCMC bin/TutorialDiagConfig.yaml MCMC_Test.root
            test_3: ./bin/DiagMCMC MCMC_Test.root bin/TutorialDiagConfig.yaml
            test_4: ./bin/GetPenaltyTerm MCMC_Test.root bin/TutorialDiagConfig.yaml
            test_5: ./bin/RHat 10 MCMC_Test.root MCMC_Test.root MCMC_Test.root MCMC_Test.root
            test_7: ./bin/CombineMaCh3Chains -o MergedChain.root MCMC_Test.root MCMC_Test.root MCMC_Test.root MCMC_Test.root

            # TODO
            #test_8: bin/GetPostfitParamPlots -o MCMC_Test_Process.root -c Inputs/PlottingConfig.yaml
            #test_9: bin/PlotLLH -o MCMC_Test.root -c Inputs/PlottingConfig.yaml

          - name: NuMCMC Tools Validations
            ntests: 1
            test_1: Apps/NuMCMCvalidations.sh

    container:
      image: ghcr.io/mach3-software/mach3:alma9latest

    steps:
    - uses: actions/checkout@v4


    - name: Get MaCh3 Validations
      run: |
        cd /opt/
        git clone https://github.com/mach3-software/MaCh3Tutorial.git MaCh3Validations
        cd MaCh3Validations
        mkdir build
        cd build
        cmake ../ -DMaCh3_Branch=${{ github.head_ref }}

    - name: Build MaCh3 Validations
      run: |
        cd /opt/MaCh3Validations/build
        make -j4 install # Build the project

    - name: Validations
      run: |
        source /opt/MaCh3Validations/build/bin/setup.MaCh3.sh
        source /opt/MaCh3Validations/build/bin/setup.MaCh3Tutorial.sh
        cd /opt/MaCh3Validations/build

        for i in $(seq 1 ${{ matrix.ntests }}); do
          echo "Running test $i: ${{ matrix.test_${{ i }} }}"
          eval ${{ matrix.test_${{ i }} }}
        done

