# Performs unit and integration testing

name: Validations CI

# The events that trigger the workflow
on:
  pull_request:
    branches: [ develop ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    name: ${{ matrix.name }}

    strategy:
      fail-fast: false  #KS: Prevents cancellation of remaining jobs if one fails
      matrix:
        include:
          - name: Spline Validations
            ntests: 1
            tests: ["Apps/SplineValidations"]

          - name: Covariance Validations
            ntests: 2
            tests: ["Apps/CovarianceValidations", "Apps/MaCh3ModeValidations"]

          - name: Fitter Validations
            ntests: 6
            tests: [
              "Apps/FitterValidations",
              "./bin/ProcessMCMC bin/TutorialDiagConfig.yaml MCMC_Test.root",
              "./bin/DiagMCMC MCMC_Test.root bin/TutorialDiagConfig.yaml",
              "./bin/GetPenaltyTerm MCMC_Test.root bin/TutorialDiagConfig.yaml",
              "./bin/RHat 10 MCMC_Test.root MCMC_Test.root MCMC_Test.root MCMC_Test.root",
              "./bin/CombineMaCh3Chains -o MergedChain.root MCMC_Test.root MCMC_Test.root MCMC_Test.root MCMC_Test.root"
              # TODO
              # bin/GetPostfitParamPlots -o MCMC_Test_Process.root -c Inputs/PlottingConfig.yaml
              # bin/PlotLLH -o MCMC_Test.root -c Inputs/PlottingConfig.yaml
            ]

          - name: NuMCMC Tools Validations
            ntests: 1
            tests: ["Apps/NuMCMCvalidations.sh"]

    container:
      image: ghcr.io/mach3-software/mach3:alma9latest

    steps:
    - uses: actions/checkout@v4

    - name: Get MaCh3 Validations
      run: |
        cd /opt/
        git clone https://github.com/mach3-software/MaCh3Tutorial.git MaCh3Validations
        cd MaCh3Validations
        mkdir build
        cd build
        cmake ../ -DMaCh3_Branch=${{ github.head_ref }}

    - name: Build MaCh3 Validations
      run: |
        cd /opt/MaCh3Validations/build
        make -j4 install # Build the project

    - name: Run Validations
      run: |
        source /opt/MaCh3Validations/build/bin/setup.MaCh3.sh
        source /opt/MaCh3Validations/build/bin/setup.MaCh3Tutorial.sh
        cd /opt/MaCh3Validations/build

        # Loop over the tests in matrix and run each one
        for i in $(seq 0 $(( ${{ matrix.ntests }} - 1 )))
        do
            echo "Running command: ${matrix.tests[i]}"
            eval "${matrix.tests[i]}"
        done


