name: Post MaCh3 Newsletter

on:
  push:
    branches:
      - feature_anotherbot
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight

# TODO Add tutorial and Machine learning thingy
jobs:
  post_discussion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history including tags

      - name: Count the total number of commits and get top contributors
        run: |
          echo "commit_count=$(git rev-list --count HEAD)" >> $GITHUB_ENV

          # Capture each contributor and handle any potential whitespace issues
          first_contributor=$(git shortlog -n -s | head -n 1 | awk '{$1=""; print $0}' | sed 's/^ *//g')
          second_contributor=$(git shortlog -n -s | head -n 2 | tail -n 1 | awk '{$1=""; print $0}' | sed 's/^ *//g')
          third_contributor=$(git shortlog -n -s | head -n 3 | tail -n 1 | awk '{$1=""; print $0}' | sed 's/^ *//g')

          # Debugging: Print the contributors to verify they are captured correctly
          echo "First Contributor: $first_contributor"
          echo "Second Contributor: $second_contributor"
          echo "Third Contributor: $third_contributor"

          # Set environment variables
          echo "first_contributor=${first_contributor}" >> $GITHUB_ENV
          echo "second_contributor=${second_contributor}" >> $GITHUB_ENV
          echo "third_contributor=${third_contributor}" >> $GITHUB_ENV

      - name: Get the most recent tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "latest_tag=${latest_tag}" >> $GITHUB_ENV


      - name: Get the current date
        run: |
          current_date=$(date +"%d/%m/%Y")
          echo "current_date=${current_date}" >> $GITHUB_ENV

      - name: Create a new GitHub Discussion
        uses: abirismyname/create-discussion@v1.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: MaCh3 Newsletter - ${{ env.current_date }}
          body: |
            It's-a me, MaChio! Welcome to the newsletter.

            Date: ${{ env.current_date }}

            Total number of commits in the MaCh3 repository: ${{ env.commit_count }}

            Top contributors:
            1. ${{ env.first_contributor }}
            2. ${{ env.second_contributor }}
            3. ${{ env.third_contributor }}

            Most recent tag: ${{ env.latest_tag }}

            Cheers,
            MaCh3-bot
          repository-id: MDEwOlJlcG9zaXRvcnkzMzEwNDk0MTY=
          category-id: DIC_kwDOE7tpyM4CgQ7H

      - name: Print discussion URL and ID
        run: |
          echo "discussion-id: ${{ steps.create-discussion.outputs.discussion-id }}"
          echo "discussion-url: ${{ steps.create-discussion.outputs.discussion-url }}"
