name: Post MaCh3 Newsletter

on:
  push:
    branches:
      - feature_anotherbot
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight

# TODO Add tutorial and Machine learning thingy
jobs:
  post_discussion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history including tags

      - name: Count the total number of commits and get top contributors
        run: |
          echo "commit_count=$(git rev-list --count HEAD)" >> $GITHUB_ENV
          top_contributors=$(git shortlog -n -s | head -n 3 | awk '{$1=""; print $0}')
          echo "top_contributors=${top_contributors}" >> $GITHUB_ENV
          echo "top_contributors=$(echo "${top_contributors}" | sed 's/^ //')" >> $GITHUB_ENV

      - name: Get the most recent tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "latest_tag=${latest_tag}" >> $GITHUB_ENV


      - name: Get the current date
        run: |
          current_date=$(date +"%d/%m/%Y")
          echo "current_date=${current_date}" >> $GITHUB_ENV

      - name: Create a new GitHub Discussion
        uses: abirismyname/create-discussion@v1.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: MaCh3 Newsletter - ${{ env.current_date }}
          body: |
            It's-a me, MaChio! Welcome to the newsletter.

            Date: ${{ env.current_date }}

            Total number of commits in the MaCh3 repository: ${{ env.commit_count }}

            Top contributors: ${{ env.top_contributors }}

            Most recent tag: ${{ env.latest_tag }}

            Cheers,
            MaCh3-bot
          repository-id: MDEwOlJlcG9zaXRvcnkzMzEwNDk0MTY=
          category-id: DIC_kwDOE7tpyM4CgQ7H

      - name: Print discussion URL and ID
        run: |
          echo "discussion-id: ${{ steps.create-discussion.outputs.discussion-id }}"
          echo "discussion-url: ${{ steps.create-discussion.outputs.discussion-url }}"
